const STORAGE_KEY='citeready-projects-v1';const BRAND_KEY='citeready-brand-v1';let sourceMode='html';let audit=null;let currentText='';
const $=id=>document.getElementById(id);const qs=(s,r=document)=>r.querySelector(s);const qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const demoHtml=`<!doctype html><html lang="ru"><head><title>Ремонт iPhone в Челябинске — FixPoint</title><meta name="description" content="Профессиональный ремонт iPhone за 60 минут. Гарантия 12 месяцев, бесплатная диагностика."><link rel="canonical" href="https://fixpoint.example/iphone-repair"><meta name="author" content="Сервисный центр FixPoint"><script type="application/ld+json">{"@context":"https://schema.org","@type":"LocalBusiness","name":"FixPoint","url":"https://fixpoint.example","telephone":"+7 900 000-00-00"}</script></head><body><main><h1>Ремонт iPhone в Челябинске</h1><p>FixPoint ремонтирует смартфоны Apple с 2018 года. Большинство работ занимает от 30 до 90 минут.</p><h2>Сколько стоит ремонт iPhone?</h2><p>Замена аккумулятора стоит от 3 500 рублей, экрана — от 7 900 рублей. Точная цена зависит от модели и повреждения.</p><h2>Почему выбирают FixPoint</h2><ul><li>Гарантия 12 месяцев</li><li>Бесплатная диагностика</li><li>Оригинальные и проверенные комплектующие</li></ul><h2>Частые вопросы</h2><h3>Можно ли отремонтировать телефон в день обращения?</h3><p>Да. Около 80% ремонтов выполняются в день обращения.</p><h3>Сохранятся ли данные?</h3><p>При замене экрана или аккумулятора пользовательские данные обычно сохраняются.</p><p>Материал обновлён 15 июля 2026 года.</p><a href="https://support.apple.com/ru-ru/iphone/repair">Официальная информация Apple</a></main></body></html>`;
function toast(message){const t=$('toast');t.textContent=message;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2400)}
function switchTab(name){qsa('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));qsa('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${name}`));window.scrollTo({top:0,behavior:'smooth'})}
qsa('.nav-btn').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));qsa('.source-btn').forEach(b=>b.onclick=()=>{sourceMode=b.dataset.source;qsa('.source-btn').forEach(x=>x.classList.toggle('active',x===b));$('htmlLabel').firstChild.textContent=sourceMode==='html'?'HTML страницы':'Текст страницы';$('pageInput').placeholder=sourceMode==='html'?'Вставьте исходный HTML или загрузите .html файл':'Вставьте основной текст страницы';});
$('fileInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;$('pageInput').value=await f.text();$('fileStatus').textContent=f.name;sourceMode='html';qsa('.source-btn').forEach(x=>x.classList.toggle('active',x.dataset.source==='html'));toast('HTML загружен')};
$('loadDemo').onclick=()=>{$('projectName').value='Демо: ремонт iPhone';$('pageUrl').value='https://fixpoint.example/iphone-repair';$('pageInput').value=demoHtml;sourceMode='html';runAudit();toast('Демо загружено')};
$('clearInput').onclick=()=>{$('pageInput').value='';$('pageUrl').value='';$('projectName').value='Новый аудит';audit=null;renderEmpty();};
$('runAudit').onclick=runAudit;$('runAuditSide').onclick=runAudit;
function cleanText(v){return String(v||'').replace(/\s+/g,' ').trim()}
function getMeta(doc,name,prop=false){const sel=prop?`meta[property="${name}"]`:`meta[name="${name}"]`;return cleanText(doc.querySelector(sel)?.content)}
function parseSchema(doc){const items=[];qsa('script[type="application/ld+json"]',doc).forEach(s=>{try{const j=JSON.parse(s.textContent);const arr=Array.isArray(j)?j:[j];arr.forEach(x=>{if(x?.['@graph'])x['@graph'].forEach(g=>items.push(g));else items.push(x)})}catch{}});return items}
function sentenceCount(text){return (text.match(/[.!?]+(?:\s|$)/g)||[]).length}
function extractYear(text){const years=(text.match(/20(?:2[4-9]|3\d)/g)||[]).map(Number);return years.length?Math.max(...years):null}
function runAudit(){const raw=$('pageInput').value.trim();if(!raw){toast('Добавьте HTML или текст страницы');return}let doc,text;if(sourceMode==='html'){doc=new DOMParser().parseFromString(raw,'text/html');qsa('script,style,noscript,svg',doc).forEach(n=>n.remove());text=cleanText(doc.body?.innerText||doc.body?.textContent)}else{doc=document.implementation.createHTMLDocument('');doc.body.innerHTML=`<main><h1>${escapeHtml($('projectName').value)}</h1><p>${escapeHtml(raw)}</p></main>`;text=cleanText(raw)}currentText=text;audit=analyze(doc,text);renderAudit();generateAssets();switchTab('report');}
function analyze(doc,text){const title=cleanText(doc.title),description=getMeta(doc,'description'),robots=getMeta(doc,'robots').toLowerCase();const canonical=doc.querySelector('link[rel="canonical"]')?.href||'';const lang=doc.documentElement.lang||'';const h1=qsa('h1',doc).map(x=>cleanText(x.textContent)).filter(Boolean);const headings=qsa('h2,h3',doc).map(x=>cleanText(x.textContent)).filter(Boolean);const paragraphs=qsa('p',doc).map(x=>cleanText(x.textContent)).filter(x=>x.length>20);const links=qsa('a[href]',doc);const external=links.filter(a=>{try{return new URL(a.href,'https://local.invalid').hostname!=='local.invalid'&&!a.href.startsWith('#')}catch{return false}});const images=qsa('img',doc);const missingAlt=images.filter(i=>!cleanText(i.alt)).length;const schema=parseSchema(doc);const schemaTypes=[...new Set(schema.flatMap(x=>Array.isArray(x?.['@type'])?x['@type']:[x?.['@type']]).filter(Boolean))];const questions=[...new Set([...headings.filter(h=>/[?？]$/.test(h)),...(text.match(/[^.!?]{12,90}\?/g)||[]).map(cleanText)])].slice(0,12);const lists=qsa('ul,ol',doc).length,tables=qsa('table',doc).length;const words=text.split(/\s+/).filter(Boolean).length;const author=getMeta(doc,'author')||schema.find(x=>x.author)?.author?.name||'';const dates=[getMeta(doc,'article:published_time',true),getMeta(doc,'article:modified_time',true),...schema.flatMap(x=>[x.datePublished,x.dateModified])].filter(Boolean);const year=extractYear(text);const avgP=paragraphs.length?Math.round(paragraphs.reduce((a,p)=>a+p.split(/\s+/).length,0)/paragraphs.length):0;const concise=paragraphs.filter(p=>{const w=p.split(/\s+/).length;return w>=20&&w<=65}).length;const faqSchema=schemaTypes.includes('FAQPage');const orgSchema=schemaTypes.some(x=>['Organization','LocalBusiness','Person'].includes(x));const contact=/(контакт|contact|телефон|phone|email|почт)/i.test(text);const claims=(text.match(/\b\d+(?:[.,]\d+)?\s*(?:%|лет|год|дн|час|₽|руб|евро|доллар)/gi)||[]).length;
 const cats={crawl:{label:'Доступность',score:0},structure:{label:'Структура',score:0},answer:{label:'Ответность',score:0},trust:{label:'Доверие',score:0},fresh:{label:'Свежесть',score:0}};const issues=[];const add=(sev,cat,title,fix,quick=false)=>issues.push({sev,cat,title,fix,quick});
 if(title&&title.length>=20&&title.length<=70)cats.crawl.score+=4;else add('warning','crawl','Title отсутствует или имеет неудачную длину','Добавьте уникальный title длиной примерно 20–70 символов.',true);
 if(description&&description.length>=70&&description.length<=180)cats.crawl.score+=4;else add('warning','crawl','Meta description требует доработки','Сформулируйте описание страницы в 70–180 символов.',true);
 if(canonical)cats.crawl.score+=4;else add('warning','crawl','Не найден canonical','Добавьте link rel="canonical" с основным URL страницы.',true);
 if(!robots.includes('noindex'))cats.crawl.score+=4;else add('critical','crawl','Страница закрыта от индексации','Уберите noindex, если страница должна появляться в поиске.');
 if(lang)cats.crawl.score+=4;else add('warning','crawl','Не указан язык документа','Добавьте атрибут lang к тегу html.',true);
 if(h1.length===1)cats.structure.score+=4;else add(h1.length===0?'critical':'warning','structure',h1.length===0?'Нет H1':'Несколько H1',h1.length===0?'Добавьте один основной заголовок H1.':'Оставьте один основной H1, остальные понизьте до H2/H3.');
 if(headings.length>=3)cats.structure.score+=4;else add('warning','structure','Слабая иерархия разделов','Разбейте материал минимум на 3 смысловых раздела H2/H3.');
 if(lists+tables>0)cats.structure.score+=4;else add('info','structure','Нет списков или таблиц','Добавьте структурированный список, сравнительную таблицу или пошаговый блок.',true);
 if(schemaTypes.length)cats.structure.score+=4;else add('warning','structure','Нет структурированных данных','Добавьте релевантный Schema.org JSON-LD.');
 if(missingAlt===0)cats.structure.score+=4;else add('warning','structure',`${missingAlt} изображений без alt`,'Добавьте содержательные alt-описания важным изображениям.',true);
 if(words>=500)cats.answer.score+=4;else add('warning','answer','Недостаточная глубина материала','Раскройте тему подробнее: ориентир 500+ слов для информационной страницы.');
 if(questions.length>=2)cats.answer.score+=4;else add('warning','answer','Мало явно сформулированных вопросов','Добавьте вопросы аудитории в H2/H3 и дайте прямой ответ сразу под ними.');
 if(concise>=3)cats.answer.score+=4;else add('info','answer','Мало коротких ответных абзацев','Добавьте 3–5 абзацев по 20–65 слов, каждый отвечает на один вопрос.',true);
 if(faqSchema)cats.answer.score+=4;else add('info','answer','Нет FAQPage schema','Сгенерируйте FAQ JSON-LD для реальных вопросов на странице.',true);
 if(lists+tables>=2)cats.answer.score+=4;else add('info','answer','Недостаточно сканируемых форматов','Используйте списки, таблицы, определения и пошаговые инструкции.');
 if(author)cats.trust.score+=4;else add('warning','trust','Не указан автор или организация','Добавьте автора, редактора или ответственную организацию.');
 if(external.length>=1)cats.trust.score+=4;else add('warning','trust','Нет внешних подтверждающих источников','Сошлитесь на первичные или авторитетные источники.');
 if(orgSchema)cats.trust.score+=4;else add('info','trust','Нет Organization/Person schema','Добавьте данные об организации или авторе в JSON-LD.',true);
 if(contact)cats.trust.score+=4;else add('info','trust','Не видны контактные или редакционные данные','Добавьте контакты, страницу «О компании» или редакционную политику.');
 if(claims===0||external.length>0)cats.trust.score+=4;else add('warning','trust','Числовые утверждения без видимого источника','Подкрепите статистику ссылками и укажите дату данных.');
 if(dates.length)cats.fresh.score+=8;else add('warning','fresh','Нет даты публикации или обновления','Покажите datePublished/dateModified и добавьте их в Article schema.');
 const now=new Date().getFullYear();if(year&&year>=now-1)cats.fresh.score+=6;else add('info','fresh','Не обнаружен свежий временной контекст','Обновите примеры, тарифы, статистику и дату материала.');
 if(/обновл|актуал|редакц/i.test(text))cats.fresh.score+=6;else add('info','fresh','Нет признака редакционного обновления','Добавьте заметку о последней проверке или обновлении.');
 const score=Math.round(Object.values(cats).reduce((a,c)=>a+c.score,0));const rank={critical:0,warning:1,info:2};const ordered=issues.sort((a,b)=>rank[a.sev]-rank[b.sev]);return{score,cats,issues:ordered,signals:{title:title||'—',description:description||'—',canonical:canonical||$('pageUrl').value||'—',h1:h1[0]||'—',words,headings:headings.length,questions:questions.length,schema:schemaTypes.join(', ')||'Нет',external:external.length,images:images.length,missingAlt,avgParagraph:avgP,author:author||'—',dates:dates.join(', ')||'—'},questions,headings,paragraphs,title,description,canonical,words,schemaTypes};}
function verdict(score){if(score>=85)return['Готово к масштабированию','Страница хорошо структурирована. Остаётся точечно усилить доверие и coverage.'];if(score>=70)return['Сильная база','Страница понятна поисковым системам, но несколько пробелов снижают шанс цитирования.'];if(score>=50)return['Требуется доработка','Есть базовые сигналы, но ответность, доверие или техническая разметка недостаточны.'];return['Высокий риск невидимости','Странице сложно доверять, извлекать ответы или корректно интерпретировать её структуру.'];}
function renderAudit(){const [v,t]=verdict(audit.score);$('heroScore').textContent=audit.score;$('heroVerdict').textContent=v;$('scoreValue').textContent=audit.score;$('scoreRing').style.background=`conic-gradient(var(--accent) ${audit.score*3.6}deg,#263142 0deg)`;$('verdict').textContent=v;$('verdictText').textContent=t;$('criticalCount').textContent=audit.issues.filter(x=>x.sev==='critical').length;$('warningCount').textContent=audit.issues.filter(x=>x.sev==='warning').length;$('quickWinCount').textContent=audit.issues.filter(x=>x.quick).length;$('reportTitle').textContent=$('projectName').value||audit.title||'Аудит';$('reportUrl').textContent=$('pageUrl').value||audit.canonical||'Локальный HTML';$('reportScore').textContent=audit.score;$('reportSubtitle').textContent=`${$('projectName').value} · ${new Date().toLocaleDateString('ru-RU')}`;$('categoryGrid').innerHTML=Object.values(audit.cats).map(c=>`<article class="category-card"><span>${c.label}</span><strong>${c.score}/20</strong><div class="progress"><i style="width:${c.score*5}%"></i></div></article>`).join('');$('issuesList').innerHTML=audit.issues.length?audit.issues.map(i=>`<article class="issue"><div class="issue-head"><span class="severity ${i.sev}">${i.sev==='critical'?'КРИТИЧНО':i.sev==='warning'?'ВАЖНО':'УЛУЧШЕНИЕ'}</span><small>${audit.cats[i.cat].label}</small></div><h3>${i.title}</h3><p>${i.fix}</p></article>`).join(''):'<div class="empty">Критичных проблем не обнаружено</div>';$('actionPlan').innerHTML=audit.issues.slice(0,8).map((i,n)=>`<article class="action"><div class="action-index">${n+1}</div><div><h3>${i.title}</h3><p>${i.fix}</p></div></article>`).join('');const s=audit.signals;$('signalsGrid').innerHTML=[['Title',s.title],['H1',s.h1],['Слов',s.words],['H2/H3',s.headings],['Вопросов',s.questions],['Schema',s.schema],['Внешних ссылок',s.external],['Средний абзац',`${s.avgParagraph} слов`],['Автор',s.author],['Дата',s.dates],['Изображений',s.images],['Без alt',s.missingAlt]].map(x=>`<div class="signal"><span>${x[0]}</span><strong>${escapeHtml(String(x[1]))}</strong></div>`).join('');}
function renderEmpty(){$('heroScore').textContent='—';$('scoreValue').textContent='—';$('heroVerdict').textContent='Загрузите HTML или используйте демо';$('scoreRing').style.background='conic-gradient(var(--accent) 0deg,#263142 0deg)';}
function generateAssets(){const qs=audit.questions.length?audit.questions:audit.headings.filter(h=>h.length<100).slice(0,6).map(h=>h.endsWith('?')?h:`Что важно знать про «${h}»?`);const pairs=qs.slice(0,8).map((q,i)=>({q,a:audit.paragraphs[i]||`Добавьте прямой ответ на вопрос «${q}» длиной 40–70 слов, затем подтвердите его деталями и источниками.`}));$('faqOutput').value=JSON.stringify({'@context':'https://schema.org','@type':'FAQPage','mainEntity':pairs.map(x=>({'@type':'Question','name':x.q,'acceptedAnswer':{'@type':'Answer','text':x.a}}))},null,2);const url=$('pageUrl').value||audit.canonical||'https://example.com/page';$('llmsOutput').value=`# ${audit.title||$('projectName').value}\n\n> ${audit.description||audit.paragraphs[0]||'Краткое описание страницы.'}\n\n## Canonical URL\n${url}\n\n## Key topics\n${audit.headings.slice(0,8).map(h=>`- ${h}`).join('\n')||'- Основная тема страницы'}\n\n## Important facts\n${audit.paragraphs.slice(0,5).map(p=>`- ${p}`).join('\n')}\n\n## Contact and attribution\n- Author/organization: ${audit.signals.author}\n- Last reviewed: ${new Date().toISOString().slice(0,10)}`;$('answersOutput').value=pairs.map(x=>`${x.q}\n${x.a}\n`).join('\n');$('briefOutput').value=`CONTENT BRIEF: ${audit.title||$('projectName').value}\n\nЦЕЛЬ\nСделать страницу понятной пользователю и пригодной для извлечения точных ответов поисковыми и AI-системами.\n\nПРИОРИТЕТЫ\n${audit.issues.slice(0,8).map((x,i)=>`${i+1}. ${x.title}: ${x.fix}`).join('\n')}\n\nРЕКОМЕНДУЕМАЯ СТРУКТУРА\n- Короткий ответ/определение в первых 80 словах\n${pairs.slice(0,6).map(x=>`- ${x.q}`).join('\n')}\n- Таблица или пошаговый список\n- Автор, дата обновления и первичные источники\n\nКОНТРОЛЬ КАЧЕСТВА\n- Один H1\n- Вопросы в H2/H3\n- Ответ 40–70 слов сразу после вопроса\n- Ссылки на первичные источники\n- Релевантный Schema.org JSON-LD\n- Проверка актуальности чисел и дат`;}
qsa('.copy-btn').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText($(b.dataset.copy).value);toast('Скопировано')});
function getProjects(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}}
$('saveProject').onclick=()=>{if(!audit){toast('Сначала выполните аудит');return}const all=getProjects();const item={id:crypto.randomUUID?.()||Date.now().toString(),name:$('projectName').value,url:$('pageUrl').value,created:new Date().toISOString(),audit,raw:$('pageInput').value,sourceMode};all.unshift(item);localStorage.setItem(STORAGE_KEY,JSON.stringify(all.slice(0,30)));renderProjects();toast('Проект сохранён')};
function renderProjects(){const all=getProjects();$('projectsGrid').innerHTML=all.length?all.map(p=>`<article class="project-card"><span class="eyebrow">${new Date(p.created).toLocaleDateString('ru-RU')}</span><div class="project-score">${p.audit.score}</div><h3>${escapeHtml(p.name)}</h3><p class="muted">${escapeHtml(p.url||'Локальный HTML')}</p><footer><button class="button ghost" data-open="${p.id}">Открыть</button><button class="button ghost" data-delete="${p.id}">Удалить</button></footer></article>`).join(''):'<div class="empty panel">Сохранённых проектов пока нет</div>';qsa('[data-open]').forEach(b=>b.onclick=()=>openProject(b.dataset.open));qsa('[data-delete]').forEach(b=>b.onclick=()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(all.filter(x=>x.id!==b.dataset.delete)));renderProjects();toast('Удалено')});}
function openProject(id){const p=getProjects().find(x=>x.id===id);if(!p)return;$('projectName').value=p.name;$('pageUrl').value=p.url;$('pageInput').value=p.raw;sourceMode=p.sourceMode;audit=p.audit;renderAudit();generateAssets();switchTab('report')}
function download(name,content,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('exportJson').onclick=()=>audit?download('citeready-audit.json',JSON.stringify(audit,null,2)):toast('Нет отчёта');$('exportCsv').onclick=()=>{if(!audit)return toast('Нет отчёта');const rows=[['Severity','Category','Issue','Fix'],...audit.issues.map(i=>[i.sev,audit.cats[i.cat].label,i.title,i.fix])];download('citeready-issues.csv',rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')};$('printReport').onclick=()=>window.print();$('exportAll').onclick=()=>download('citeready-projects.json',JSON.stringify(getProjects(),null,2));
$('applyBrand').onclick=()=>{const brand={name:$('agencyName').value,contact:$('agencyContact').value,color:$('accentColor').value,footer:$('footerText').value};localStorage.setItem(BRAND_KEY,JSON.stringify(brand));applyBrand(brand);toast('Брендинг применён')};function applyBrand(b){document.documentElement.style.setProperty('--accent',b.color||'#7cff9b');$('previewAgency').textContent=b.name;$('previewContact').textContent=b.contact;$('previewFooter').textContent=b.footer;$('reportBrand').textContent=`${b.name} · ${b.contact}`}
function loadBrand(){try{const b=JSON.parse(localStorage.getItem(BRAND_KEY)||'null');if(b){$('agencyName').value=b.name;$('agencyContact').value=b.contact;$('accentColor').value=b.color;$('footerText').value=b.footer;applyBrand(b)}}catch{}}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
renderProjects();loadBrand();